#cloud-config
packages:
  - nginx

write_files:
  - path: /etc/nginx/sites-available/reverse-proxy
    permissions: '0644'
    content: |
      server {
          listen 80;
          server_name gitlab.mydomain.com;

          location / {
              proxy_pass http://${gitlab_ip};
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      }
      server {
          listen 80;
          server_name nexus.mydomain.com;

          location / {
              proxy_pass http://${nexus_ip};
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      }

runcmd:
  - sudo ln -s /etc/nginx/sites-available/reverse-proxy /etc/nginx/sites-enabled/
  - sudo systemctl restart nginx
