#cloud-config
packages:
  - openvpn
  - easy-rsa

write_files:
  - path: /etc/openvpn/server.conf
    content: |
      port 1194
      proto udp
      dev tun
      ca ca.crt
      cert server.crt
      key server.key
      dh dh2048.pem
      server 10.8.0.0 255.255.255.0
      push "route 10.0.2.0 255.255.255.0"
      persist-key
      persist-tun
      status openvpn-status.log
      verb 3

  - path: /etc/openvpn/easy-rsa/vars
    content: |
      set_var EASYRSA_KEY_SIZE 2048
      set_var EASYRSA_CA_EXPIRE 3650
      set_var EASYRSA_CERT_EXPIRE 3650
      set_var EASYRSA_REQ_COUNTRY "FR"
      set_var EASYRSA_REQ_PROVINCE "IDF"
      set_var EASYRSA_REQ_CITY "Paris"
      set_var EASYRSA_REQ_ORG "Clement-VPN"
      set_var EASYRSA_REQ_EMAIL "admin@clement.net"
      set_var EASYRSA_REQ_OU "CICD"

runcmd:
  - cd /etc/openvpn/easy-rsa
  - ./easyrsa init-pki
  - ./easyrsa build-ca nopass
  - ./easyrsa build-server-full server nopass
  - ./easyrsa gen-dh
  - openvpn --genkey --secret /etc/openvpn/ta.key
  - cp pki/ca.crt pki/issued/server.crt pki/private/server.key /etc/openvpn/
  - cp dh.pem /etc/openvpn/dh2048.pem
  - systemctl start openvpn@server
  - systemctl enable openvpn@server
