#cloud-config

package_update: true
packages:
  - wireguard

write_files:
  - path: /etc/wireguard/wg0.conf
    permissions: '0600'
    owner: root:root
    content: |
      [Interface]
      Address = 10.8.0.1/24
      SaveConfig = true
      ListenPort = 51820
      PrivateKey = REPLACE_WITH_PRIVATE_KEY
      PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o enX0 -j MASQUERADE
      PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -o enX0 -j MASQUERADE

runcmd:
  # 1. Créer le dossier /etc/wireguard
  - mkdir -p /etc/wireguard

  # 2. Générer la paire de clés (privée + publique)
  - wg genkey | tee /etc/wireguard/privatekey | wg pubkey | tee /etc/wireguard/publickey
  - chmod 600 /etc/wireguard/privatekey /etc/wireguard/publickey

  # 3. Remplacer le placeholder par la vraie clé privée
  - sed -i "s|REPLACE_WITH_PRIVATE_KEY|$(cat /etc/wireguard/privatekey)|" /etc/wireguard/wg0.conf

  # 4. Activer l'IP forwarding
  - echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
  - sysctl -p

  # 5. Activer et démarrer le service
  - systemctl enable wg-quick@wg0
  - systemctl start wg-quick@wg0

  # (Optionnel) Afficher l'état de WireGuard pour debug
  - wg show
