#cloud-config
packages:
  - wireguard

runcmd:
  # 1. Créer le dossier /etc/wireguard
  - mkdir -p /etc/wireguard/
  - cd /etc/wireguard/

  # 2. Générer la paire de clés (privée + publique)
  - wg genkey | tee /etc/wireguard/privatekey | wg pubkey | tee /etc/wireguard/publickey
  - chmod 600 /etc/wireguard/privatekey /etc/wireguard/publickey

  # 3. Activer l'IP forwarding
  - bash -c 'echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf'
  - sysctl -p

  # 4. Créer le fichier de configuration WireGuard
  - bash -c "PRIVATE_KEY=\$(cat /etc/wireguard/privatekey); cat <<EOF > /etc/wireguard/wg0.conf
[Interface]
Address = 10.0.0.1/24
SaveConfig = true
ListenPort = 51820
PrivateKey = \$PRIVATE_KEY
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
EOF"

  # 5. Activer et démarrer le service
  - systemctl enable wg-quick@wg0
  - systemctl start wg-quick@wg0

  # (Optionnel) Afficher l'état de WireGuard pour debug
  - wg show
