#cloud-config

packages:
  - curl
  - openssh-server
  - ca-certificates
  - postfix
  - git
  - gitlab-ee

write_files:
  - path: /etc/gitlab/gitlab.rb
    permissions: '0644'
    content: $${config_content}


runcmd:
  - gitlab-ctl reconfigure